shop/pages/urls.py
from django.contrib import admin
from django.urls import path
from .views import *


app_name = 'pages'

urlpatterns = [

    path('', index, name='index'),
    path('sales', sales, name='sales'),
    path('thanks', thanks, name='thanks'),
    path('cat/<str:slug>/', category_view, name='category_view'),
    path('view/<str:slug_prod>', single, name='single'),
    path('info/<str:page_slug>', pages, name='pages'),
    path('basket/add/<int:product_id>', add_to_basket, name='add_to_basket'),
    path('basket/remove/<int:basket_id>/<int:prod_id>/<str:size>/<str:color>', remove_basket, name='remove_basket')

]

shop/shop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.views.static import serve



urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("pages.urls", namespace='pages')),
    path('users/', include("users.urls", namespace='users')),

]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root= settings.MEDIA_ROOT)
else:
    urlpatterns += [
        path(f'^{settings.MEDIA_URL.lstrip("/")}(?P<path>.*)$', serve , {"document_root":settings.MEDIA_ROOT}),
        path(f'^{settings.STATIC_URL.lstrip("/")}(?P<path>.*)$', serve, {"document_root": settings.STATIC_ROOT}),
    ]

shop/users/urls.py
from django.contrib import admin
from django.urls import path
from .views import *

app_name = 'users'

urlpatterns = [

    #path('', single, name='single'),
    path('login/', login, name='login'),
    path('logout/', logout, name='logout'),
    path('register/', register, name='register'),
    path('basket/', basket, name='basket'),
]

shop/pages/templates/pages/cats.html
{% extends 'pages/index2.html'%}
{% load static %}

{% block title %}
<title>Магія | {{cat.title}}</title>
<meta name="description" content='{{cat.page_description}}'>
<meta name="keywords" content='{{cat.page_keywords}}'>
{% endblock %}

{% block body %}

{% if products %}
        <!-- BLOGS ENTRY START -->
        <section class="contained">
            <h2 class="section-title ff-damion">{{cat.title}}</h2>
            <p class="ta-center col-wide mlmr-a">
                {{cat.page_description}}
            </p>
            <div class="row flex-just-center">
                {% for prod in products %}
                <div class="col-quad">
                    <article class="card-blog ">
                        <a href="{% url 'pages:single' slug_prod=prod.slug %}" class="">

                            <img src="{{prod.image.url}}" alt="">


                            <div class="info">
                                <h3 class="lt-1 mt-5 mb-5 ff-damion fc-primary">{{prod.title}}</h3>
                                <p class="ml-a mt-5">{% if prod.sale %}

                                    <s>{{prod.price}}</s> {{prod.prise_on_sale}} {% else %} {{prod.price}} {%endif%}грн.</p>
                            </div>
                            <p class="ml-10 mt-5 mb-20 lt-3">
                                {{prod.short_description}}
                            </p>

                                 <i class="btn-bg1 border-round">Більше інформації</i>
                        </a>
                    </article>
                </div>
                {%endfor%}
            </div>
        </section>
{% else %}
        <section class="contained">
            <h2 class="section-title ff-damion">{{cat.title}}</h2>
            <h3 class="ta-center col-wide mlmr-a">
                На данний момент в цій категорії немає товарів, спробуйте зазирнути пізніше
            </h3>
        </section>
{% endif %}
  {% endblock %}

shop/pages/templates/pages/index.html
<!doctype html>

{% load static %}

<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="{% static 'css/mdb.dark.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/mdb.dark.rtl.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/mdb.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/mdb.rtl.min.css' %}">

    <link rel="stylesheet" href="{% static 'css/style.css' %}">

    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">

    {% block title%}

    {% endblock %}
</head>
<body>





<!-- Navbar -->
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <!-- Container wrapper -->
  <div class="container-fluid">
    <!-- Toggle button -->
    <button
      data-mdb-collapse-init
      class="navbar-toggler"
      type="button"
      data-mdb-target="#navbarSupportedContent"
      aria-controls="navbarSupportedContent"
      aria-expanded="false"
      aria-label="Toggle navigation"
    >
      <i class="fas fa-bars"></i>
    </button>

    <!-- Collapsible wrapper -->
    <div class="collapse navbar-collapse " id="navbarSupportedContent">
      <!-- Navbar brand -->
      <a class="navbar-brand mt-2 mt-lg-0 bg-light" href="{% url 'pages:index' %}">
        <img
          src="https://mdbcdn.b-cdn.net/img/logo/mdb-transaprent-noshadows.webp"
          height="15"
          alt="MDB Logo"
          loading="lazy"
        />
      </a>
      <!-- Left links -->
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link" href="#">Dashboard</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">Team</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">Projects</a>
        </li>
      </ul>
      <!-- Left links -->
    </div>
    <!-- Collapsible wrapper -->

    <!-- Right elements -->
    <div class="d-flex align-items-center">
      <!-- Icon -->
      <a class="text-reset me-3" href="#">
        <i class="fas fa-shopping-cart"></i>
      </a>

      <!-- Notifications -->
      <div class="dropdown">
        <a
          data-mdb-dropdown-init
          class="text-reset me-3 dropdown-toggle hidden-arrow"
          href="#"
          id="navbarDropdownMenuLink"
          role="button"
          aria-expanded="false"
        >
          <i class="fas fa-bell"></i>
          <span class="badge rounded-pill badge-notification bg-danger"></span>
        </a>
        <ul
          class="dropdown-menu dropdown-menu-end"
          aria-labelledby="navbarDropdownMenuLink"
        >
          <li>
            <a class="dropdown-item" href="#">Some news</a>
          </li>
          <li>
            <a class="dropdown-item" href="#">Another news</a>
          </li>
          <li>
            <a class="dropdown-item" href="#">Something else here</a>
          </li>
        </ul>
      </div>
      <!-- Avatar -->
      <div class="dropdown">
        <a
          data-mdb-dropdown-init
          class="dropdown-toggle d-flex align-items-center hidden-arrow"
          href="#"
          id="navbarDropdownMenuAvatar"
          role="button"
          aria-expanded="false"
        >
          <img
            src="https://mdbcdn.b-cdn.net/img/new/avatars/2.webp"
            class="rounded-circle"
            height="25"
            alt="Black and White Portrait of a Man"
            loading="lazy"
          />
        </a>
        <ul
          class="dropdown-menu dropdown-menu-end"
          aria-labelledby="navbarDropdownMenuAvatar"
        >
          {% if user.is_authenticated %}
          <li>
            <a class="dropdown-item" href="{% url 'users:single' %}">My profile</a>
          </li>
          <li>
            <li>
            <a class="dropdown-item" href="{% url 'users:logout' %}">Logout</a>
          </li>
          <li>
            <a class="dropdown-item" href="{% url 'users:basket' %}">Cart</a>
          </li>
            {% else %}
            <a class="dropdown-item" href="{% url 'users:register' %}">Register</a>
          </li>
          <li>
            <a class="dropdown-item" href="{% url 'users:login' %}">Login</a>
          </li>
          {% endif %}
        </ul>
      </div>
    </div>
    <!-- Right elements -->
  </div>
  <!-- Container wrapper -->
</nav>
<!-- Navbar -->

    {% block body%}

    {% endblock %}




<!-- Footer -->
<foot class="text-center text-lg-start bg-body-tertiary text-muted bg-dark">
  <!-- Section: Social media -->
  <section class="d-flex justify-content-center justify-content-lg-between p-4 border-bottom bg-dark">
    <!-- Left -->
    <div class="me-5 d-none d-lg-block">
      <span>Get connected with us on social networks:</span>
    </div>
    <!-- Left -->

    <!-- Right -->
    <div>
      <a href="" class="me-4 text-reset">
        <i class="fab fa-facebook-f"></i>
      </a>
      <a href="" class="me-4 text-reset">
        <i class="fab fa-twitter"></i>
      </a>
      <a href="" class="me-4 text-reset">
        <i class="fab fa-google"></i>
      </a>
      <a href="" class="me-4 text-reset">
        <i class="fab fa-instagram"></i>
      </a>
      <a href="" class="me-4 text-reset">
        <i class="fab fa-linkedin"></i>
      </a>
      <a href="" class="me-4 text-reset">
        <i class="fab fa-github"></i>
      </a>
    </div>
    <!-- Right -->
  </section>
  <!-- Section: Social media -->

  <!-- Section: Links  -->
  <section class="">
    <div class="container text-center text-md-start mt-5">
      <!-- Grid row -->
      <div class="row mt-3">
        <!-- Grid column -->
        <div class="col-md-3 col-lg-4 col-xl-3 mx-auto mb-4">
          <!-- Content -->
          <h6 class="text-uppercase fw-bold mb-4">
            <i class="fas fa-gem me-3"></i>Company name
          </h6>
          <p>
            Here you can use rows and columns to organize your footer content. Lorem ipsum
            dolor sit amet, consectetur adipisicing elit.
          </p>
        </div>
        <!-- Grid column -->

        <!-- Grid column -->
        <div class="col-md-2 col-lg-2 col-xl-2 mx-auto mb-4">
          <!-- Links -->
          <h6 class="text-uppercase fw-bold mb-4">
            Products
          </h6>
          <p>
            <a href="#!" class="text-reset">Angular</a>
          </p>
          <p>
            <a href="#!" class="text-reset">React</a>
          </p>
          <p>
            <a href="#!" class="text-reset">Vue</a>
          </p>
          <p>
            <a href="#!" class="text-reset">Laravel</a>
          </p>
        </div>
        <!-- Grid column -->

        <!-- Grid column -->
        <div class="col-md-3 col-lg-2 col-xl-2 mx-auto mb-4">
          <!-- Links -->
          <h6 class="text-uppercase fw-bold mb-4">
            Useful links
          </h6>
          <p>
            <a href="#!" class="text-reset">Pricing</a>
          </p>
          <p>
            <a href="#!" class="text-reset">Settings</a>
          </p>
          <p>
            <a href="#!" class="text-reset">Orders</a>
          </p>
          <p>
            <a href="#!" class="text-reset">Help</a>
          </p>
        </div>
        <!-- Grid column -->

        <!-- Grid column -->
        <div class="col-md-4 col-lg-3 col-xl-3 mx-auto mb-md-0 mb-4">
          <!-- Links -->
          <h6 class="text-uppercase fw-bold mb-4">Contact</h6>
          <p><i class="fas fa-home me-3"></i> New York, NY 10012, US</p>
          <p>
            <i class="fas fa-envelope me-3"></i>
            info@example.com
          </p>
          <p><i class="fas fa-phone me-3"></i> + 01 234 567 88</p>
          <p><i class="fas fa-print me-3"></i> + 01 234 567 89</p>
        </div>
        <!-- Grid column -->
      </div>
      <!-- Grid row -->
    </div>
  </section>
  <!-- Section: Links  -->

  <!-- Copyright -->
  <div class="text-center p-4" style="background-color: rgba(0, 0, 0, 0.05);">
    © 2021 Copyright:
    <a class="text-reset fw-bold" href="https://mdbootstrap.com/">MDBootstrap.com</a>
  </div>
  <!-- Copyright -->
</foot>
<!-- Footer -->

</body>
<footer>
    <script type="text/javascript" src="{% static 'js/mdb.es.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/mdb.umd.min.js' %}"></script>
</footer>
</html>

shop/pages/templates/pages/index2.html
<!DOCTYPE html>

{% load static %}

<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <!-- DESCRIPTION OF THE PAGE -->


    <!-- OG IMAGE IS THE IMAGE SHOWN WHEN YOUR WEBSITE LINK IS SHARED ON SOCIAL MEDIA -->
    <meta property="og:image" content="{% static 'art/logo.png' %}">
    <meta property="og:title" content="">
    <meta name="twitter:card" content="summary_large_image">


    {% block title%}

    {% endblock %}

    <link rel="preload" href="{% static 'img/mdb-favicon.ico' %}" as="style">
    <link rel="preload" href="{% static 'css/fontstyle.css' %}" as="style">
    <link rel="preload" href="{% static 'css/layout.css' %}" as="style">
    <link rel="preload" href="{% static 'css/animation.css' %}" as="style">
    <link rel="preload" href="{% static 'css/style.css' %}" as="style">

    <link rel="stylesheet" href="{% static 'css/style2.css' %}">
    <link rel="stylesheet" href="{% static 'icons/bootstrap-icons.css' %}">
    <link rel="stylesheet" href="{% static 'css/fontstyle.css' %}">
    <link rel="stylesheet" href="{% static 'css/layout.css' %}">
    <link rel="stylesheet" href="{% static 'css/animation.css' %}">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">

    <link rel="icon" type="image/png" href="{% static 'img/mdb-favicon.ico' %}">
</head>
<body>
<span class="fade"></span>
{% block slider%}

{% endblock %}
        <!-- NAVIGATION START -->
        <nav>
            <div class="contained" style="padding: 0 20px">
                <a href="{% url 'pages:index' %}" class="logo fc-primary ff-damion row flex-alig-center">
                    <span class="fs-h2">Магія</span>
                </a>
                <input type="checkbox" name="tablet-mobile-menu" class="tab-mob-menu" aria-label="tablet and mobile menu">
                <div class="navigation-container">
                    <a href="{% url 'pages:index' %}">Головна</a>
                    {% if pages %}
                        {% for page in pages %}
                            <a href="{% url 'pages:pages' page.slug%}">{{page.title}}</a>
                        {% endfor %}
                    {% endif %}
                    {% if user.is_authenticated %}
                    <a href="{% url 'users:logout' %}">Вихід із аккаутну</a>

                    {% else %}
                    <a href="{% url 'users:register' %}">Зареєструватись</a>
                    <a href="{% url 'users:login' %}">Вхід в аккаунт</a>
                    {% endif %}
                    <a href="{% url 'users:basket' %}">Кошик 🛒
<!--                    <span class="badge">{{baskets.total_quantity}}</span>-->
                    </a>
                </div>
            </div>
        </nav>
        <a href="#" class="btn-back-to-top" aria-label="Back to top button">
            <i class="bi bi-chevron-up">↑</i>
        </a>
        <!-- NAVIGATION END -->
    {% block body%}

    {% endblock %}

</body>


    <!-- FOOTER START -->
    <footer class="fc-white">
        <div class="contained row flex-just-center">

            <!-- FOOTER WEBSITE MOTO START -->
            <div class="col-balance">
                <h3 class="ff-damion">Магія</h3>
                <p>
                    Дозвольте нам стати частиною вашого стилю і подарувати вам відчуття тепла та затишку.
                </p>

            </div>
            <!-- FOOTER WEBSITE MOTO END -->


            <!-- FOOTER SCHEDULE START -->
<!--            <div class="col-quad">-->
<!--                <h3 class="ff-damion">Opening hours</h3>-->
<!--                <p class="mt-10 mb-10 fw-bold">-->
<!--                    Monday - Friday:-->
<!--                    <span class="fw-normal display-block">Closed</span>-->
<!--                </p>-->
<!--                <p class="mt-10 mb-10 fw-bold">-->
<!--                    Saturday:-->
<!--                    <span class="fw-normal display-block">8:00 - 8:01</span>-->
<!--                </p>-->
<!--                <p class="mt-10 mb-10 fw-bold">-->
<!--                    Sunday:-->
<!--                    <span class="fw-normal display-block">10:00 - 10:01</span>-->
<!--                </p>-->
<!--            </div>-->
            <!-- FOOTER SCHEDULE END -->

            <!-- FOOTER QUICK CONTACT START -->
            <div class="col-quad">
                <h3 class="ff-damion">Завжди на зв'язку</h3>
                <a href="mailto:modniydomkristal@gmail.com" class="display-block fc-white icon-link mt-10 mb-10">
                    <i class="bi bi-envelope-fill">📧</i>
                    modniydomkristal@gmail.com
                </a>
                <a href="tel:+380503863914" class="display-block fc-white icon-link mt-10 mb-10">
                    <i class="bi bi-telephone-fill">📞</i>
                    +380 (50) 386 39 14
                </a>
<!--                <a href="#" class="display-inblock fc-white icon-link mt-20" aria-label="Follow on facebook">-->
<!--                    <i class="bi bi-facebook"></i>-->
<!--                </a>-->
<!--                <a href="#" class="display-inblock fc-white icon-link" aria-label="Follow on instagram">-->
<!--                    <i class="bi bi-instagram"></i>-->
<!--                </a>-->
<!--                <a href="#" class="display-inblock fc-white icon-link" aria-label="Follow on twitter">-->
<!--                    <i class="bi bi-twitter"></i>-->
<!--                </a>-->
<!--                <a href="#" class="display-inblock fc-white icon-link" aria-label="Follow on youtube">-->
<!--                    <i class="bi bi-youtube"></i>-->
<!--                </a>-->
            </div>
            <!-- FOOTER QUICK CONTACT END -->


            <!-- FOOTER USEFUL LINKS START -->
            <div class="col-quad">
                <h3 class="ff-damion">Корисні посилання</h3>
                {% if pages %}
                        {% for page in pages %}
                <a href="{% url 'pages:pages' page.slug%}" class="display-block fc-white mt-5 mb-5">
                    <i class="bi bi-chevron-compact-right"></i>
                    {{page.title}}
                </a>
                        {% endfor %}
                    {% endif %}


            </div>
            <!-- FOOTER USEFUL LINKS END -->

        </div>
        <div class="copy ta-center fc-white">
            <small>&copy; Магія - Copyright 2024</small>
        </div>
    </footer>
    <!-- FOOTER END -->

<script type="text/javascript" src="{% static 'js/script.js' %}"></script>
</html>

shop/pages/templates/pages/main.html
{% extends 'pages/index.html'%}
{% load static %}

{% block body %}


    {{baskets.total_quantity}}
    {{baskets.total_sum}}

<nav aria-label="breadcrumb">
  <ol class="breadcrumb">
    <li class="breadcrumb-item"><a href="/">Home</a></li>
            {% if cat %}
            <li class="breadcrumb-item">
                / <a href="{% url 'pages:category_view' slug=cat.slug %}">{{cat.title}} </a>
            </li>
            {% endif %}

  </ol>
</nav>

<div class="container">
    <div class="row">
        <div class="col-md-3">
            {% for ca in cats %}
                <a href="{% url 'pages:category_view' slug=ca.slug %}" class="btn btn-primary" data-mdb-ripple-init>{{ca.title}}</a>
            {% endfor %}
        </div>



        <div class="col-md-8">
            <div class="container"><div class="row">
            {% for prod in products %}
            <div class="card col-4 m-1">
              <div class="bg-image hover-overlay " data-mdb-ripple-init data-mdb-ripple-color="light">
                <img src="{{prod.image.url}}" class="img-fluid"/>
                <a href="{% url 'pages:single' slug_prod=prod.slug %}">
                  <div class="mask" style="background-color: rgba(251, 251, 251, 0.15);"></div>
                </a>
              </div>
              <div class="card-body">
                <h5 class="card-title">{{prod.title}}</h5>
                <p class="card-text">{{prod.description}}</p>
                <a href="#!" class="btn btn-primary" data-mdb-ripple-init>Button</a>
              </div>
            </div>
            {% endfor %}
            </div></div>
        </div>

    </div>
</div>





{% endblock %}

shop/pages/templates/pages/main2.html
{% extends 'pages/index2.html'%}
{% load static %}

{% block title %}
<title>Магія | Інтернет-магазин одягу</title>
<meta name="description" content="У нашому Модному Домі ви знайдете вироби, які підкреслять вашу індивідуальність і додадуть вашому образу особливого шарму. Кожен виріб, створений нами, унікальний, як і ви. Ми пропонуємо широкий асортимент: від затишних светрів до вишуканих аксесуарів, які стануть чудовим доповненням вашого гардероба.">
<meta name="keywords" content="Магія, светр, сукня, костюм, зв’язаний вручну, ексклюзивноа річ, справжній витвір мистецтва, одяг, стиль, комфорт, створення з душею, натуральні матеріали, найвища якість, довговічність">
{% endblock %}

{% block slider%}


    <!-- FADE OUT ANIMATION WHEN LOADED -->
    <span class="fade"></span>
    <main>
        <!-- MAIN HERO BANNER START -->
        <section class="hero-banner">
            <div class="hero-contained">
                <div class="hero-title fc-white">
                    <h1 class="ff-damion">Магія</h1>
                    <p class="fs-h4 fw-normal">
                        Ласкаво просимо до нашого Модного Дому "Магія"!
                    </p>
                    <a href="#about" class="btn-bg2 border-round mt-20">
                        Дізнатись більше <i class="bi bi-chevron-compact-right"></i>
                    </a>
                </div>
            </div>
<!--            <div class="hero-socials">-->
<!--                <a href="#" class="mt-a icon-link" aria-label="Follow us on facebook">-->
<!--                    <i class="bi bi-facebook"></i>-->
<!--                </a>-->
<!--                <a href="#" class="icon-link mt-10" aria-label="Follow us on instagram">-->
<!--                    <i class="bi bi-instagram"></i>-->
<!--                </a>-->
<!--                <a href="#" class="icon-link mt-10" aria-label="Follow us on twitter">-->
<!--                    <i class="bi bi-twitter"></i>-->
<!--                </a>-->
<!--                <a href="#" class="icon-link mt-10" aria-label="Follow us on youtube">-->
<!--                    <i class="bi bi-youtube"></i>-->
<!--                </a>-->
<!--            </div>-->
        </section>
        <!-- MAIN HERO BANNER END -->


{% endblock %}


{% block body %}


        <!-- TEAM SECTION START -->
        <section class="contained">
            <h2 class="section-title ff-damion bg-primary-foot">Категорії</h2>

            <div class="row flex-just-center">
                {% if sales %}
                <div class="col-quad"><article class="card-team">

                        <a href="{% url 'pages:sales' %}" ><img src="{{sales.image.url}}" alt=""></a>

                        <h3 class="title ff-damion">{{sales.title}}</h3>
                        <div class="info">
                            <a href="{% url 'pages:sales' %}" class="bg-primary">
                            <h3 class="ff-damion">{{sales.title}}</h3>
                            <p>
                                {{sales.page_description}}
                            </p>
                            </p></a>
                        </div>



                </article></div>
                {% endif %}
                {% for ca in cats %}
                <div class="col-quad"><article class="card-team">

                        <a href="{% url 'pages:category_view' slug=ca.slug %}" ><img src="{{ca.image.url}}" alt=""></a>

                        <h3 class="title ff-damion">{{ca.title}}</h3>
                        <div class="info">
                            <a href="{% url 'pages:category_view' slug=ca.slug %}" class="bg-primary">
                            <h3 class="ff-damion">{{ca.title}}</h3>
                            <p>
                                {{ca.page_description}}
                            </p>
                            </p></a>
                        </div>



                </article></div>
               {% endfor %}
            </div>
            <br>
        </section>

        <section class="contained">
            <h2 class="section-title ff-damion bg-primary-foot">Новинки</h2>

            <div class="row flex-just-center ">
                {% for prod in news %}
                <div class="col-quad">
                    <article class="card-blog ">
                        <a href="{% url 'pages:single' slug_prod=prod.slug %}" class="">
                            <img src="{{prod.image.url}}" alt="">


                            <div class="info">
                                <h3 class="lt-1 mt-5 mb-5 ff-damion fc-primary">{{prod.title}}</h3>
                                <p class="ml-a mt-5">{% if prod.sale %} <s>{{prod.price}}</s> {{prod.prise_on_sale}} {% else %} {{prod.price}} {%endif%}грн.</p>
                            </div>
                            <p class="ml-10 mt-5 mb-20 lt-3">
                                {{prod.short_description}}
                            </p>

                                 <i class="btn-bg1 border-round">Глянути новинку</i>
                        </a>
                    </article>
                </div>
                {%endfor%}
            </div>
        </section>
        <!-- PREVIEW BLOGS SECTION END -->

        <!-- PREVIEW BLOGS SECTION START -->
        <section class="contained">
            <h2 class="section-title ff-damion bg-primary-foot">Товари</h2>
            <div class="row flex-just-center ">
                {% for prod in products %}
                <div class="col-quad">
                    <article class="card-blog ">
                        <a href="{% url 'pages:single' slug_prod=prod.slug %}" class="">
                            <img src="{{prod.image.url}}" alt="">


                            <div class="info">
                                <h3 class="lt-1 mt-5 mb-5 ff-damion fc-primary">{{prod.title}}</h3>
                                <p class="ml-a mt-5">{% if prod.sale %} <s>{{prod.price}}</s> {{prod.prise_on_sale}} {% else %} {{prod.price}} {%endif%}грн.</p>
                            </div>
                            <p class="ml-10 mt-5 mb-20 lt-3">
                                {{prod.short_description}}
                            </p>

                                 <i class="btn-bg1 border-round">Більше інформації</i>
                        </a>
                    </article>
                </div>
                {%endfor%}
            </div>
        </section>
        <!-- PREVIEW BLOGS SECTION END -->


        <section class="contained ta-center" id="about">
            <h2 class="section-title ff-damion" >Про нас</h2>
            <p class="col-wide mlmr-a">
                Ми – команда майстрів, які створюють унікальні вироби з любов'ю та турботою. Кожен наш светр, сукня або костюм зв’язаний вручну, що робить його не просто ексклюзивною річчю, а справжнім витвором мистецтва. Ми віримо, що одяг має бути не лише стильним, але й теплим, комфортним та створеним з душею. Наші майстри використовують тільки натуральні матеріали найвищої якості, щоб кожна річ радувала вас протягом багатьох років.
</p>
            <p class="col-wide mlmr-a mt-10">
У нашому Модному Домі ви знайдете вироби, які підкреслять вашу індивідуальність і додадуть вашому образу особливого шарму. Кожен виріб, створений нами, унікальний, як і ви. Ми пропонуємо широкий асортимент: від затишних светрів до вишуканих аксесуарів, які стануть чудовим доповненням вашого гардероба.
</p>
        </section>

    </main>


{% endblock %}

shop/pages/templates/pages/single.html
{% extends 'pages/index.html'%}
{% load static %}

{% block body %}

<nav aria-label="breadcrumb">
  <ol class="breadcrumb">
    <li class="breadcrumb-item"><a href="/">Home</a></li>
            {% if cat %}
            <li class="breadcrumb-item">
                <a href="{% url 'pages:category_view' slug=cat.slug %}">{{cat.title}} </a>
            </li>
            {% endif %}
            {% if product %}
            <li class="breadcrumb-item">
                <a href="{% url 'pages:single' slug_prod=product.slug %}">{{product.title}} </a>
            </li>
            {% endif %}
  </ol>
</nav>

<img src="{{ product.image.url }}" alt="">
{{product.description}}

{% if product.sale %} {{product.prise_on_sale}} {% else %} {{product.price}} {%endif%}


<a href="{% url 'pages:add_to_basket' product.id product.id%}">By</a>


{% endblock %}