shop/pages/urls.py
from django.contrib import admin
from django.urls import path
from .views import *


app_name = 'pages'

urlpatterns = [

    path('', index, name='index'),
    path('sales', sales, name='sales'),
    path('thanks', thanks, name='thanks'),
    path('cat/<str:slug>/', category_view, name='category_view'),
    path('view/<str:slug_prod>', single, name='single'),
    path('info/<str:page_slug>', pages, name='pages'),
    path('basket/add/<int:product_id>', add_to_basket, name='add_to_basket'),
    path('basket/remove/<int:basket_id>/<int:prod_id>/<str:size>/<str:color>', remove_basket, name='remove_basket')

]

shop/shop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.views.static import serve



urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("pages.urls", namespace='pages')),
    path('users/', include("users.urls", namespace='users')),

]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root= settings.MEDIA_ROOT)
else:
    urlpatterns += [
        path(f'^{settings.MEDIA_URL.lstrip("/")}(?P<path>.*)$', serve , {"document_root":settings.MEDIA_ROOT}),
        path(f'^{settings.STATIC_URL.lstrip("/")}(?P<path>.*)$', serve, {"document_root": settings.STATIC_ROOT}),
    ]

shop/users/urls.py
from django.contrib import admin
from django.urls import path
from .views import *

app_name = 'users'

urlpatterns = [

    #path('', single, name='single'),
    path('login/', login, name='login'),
    path('logout/', logout, name='logout'),
    path('register/', register, name='register'),
    path('basket/', basket, name='basket'),
]

shop/users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser


class User(AbstractUser):
    image = models.ImageField(upload_to="user_photos", blank=True, null=True)

shop/users/forms.py
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm, UserChangeForm
from django import forms
from .models import User

class UserLoginForm(AuthenticationForm):
    username = forms.CharField(widget=forms.TextInput(attrs={
        'type':"text" ,"id":"message-name" , 'placeholder':"Your name" ,'aria-label':"Ім'я"
    }))
    password = forms.CharField(widget=forms.TextInput(attrs={
        'type':"password" , 'class':'ml-a', 'placeholder':"Your password" ,'aria-label':"Пароль"
    }))
    

    class Meta:
        model = User
        fields = ('username','password',)

class UserRegistrationForm(UserCreationForm):
    first_name = forms.CharField(widget=forms.TextInput(attrs={
        'type':"text" ,'class':'','placeholder':"Ім'я"
    }))
    last_name = forms.CharField(widget=forms.TextInput(attrs={
        'type':"text" ,'class':'ml-a','placeholder':'Прізвище'
    }))
    username = forms.CharField(widget=forms.TextInput(attrs={
        'type':"text" ,'class':'','placeholder':'Нікнейм'
    }))
    email = forms.CharField(widget=forms.EmailInput(attrs={
        'type':"email" ,'class':'ml-a','placeholder':'Електронна пошта'
    }))
    password1 = forms.CharField(widget=forms.PasswordInput(attrs={
        'type':"password" ,'class':'','placeholder':'Пароль'
    }))
    password2 = forms.CharField(widget=forms.PasswordInput(attrs={
        'type':"password" ,'class':'ml-a','placeholder':'Ще раз пароль'
    }))
    class Meta:
        model = User
        fields = ('first_name','last_name','username', 'email', 'password1', 'password2',)

class UserCangeDataForm(UserChangeForm):
    class Meta:
        model = User
        fields = ('first_name','last_name','image', 'username', 'email',)

    first_name = forms.CharField(widget=forms.TextInput(attrs={
        'class':'form-control','placeholder':''
    }))
    last_name = forms.CharField(widget=forms.TextInput(attrs={
        'class':'form-control','placeholder':''
    }))
    image = forms.ImageField(widget=forms.FileInput(attrs={
        'class': '', 'placeholder': ''
    }), required=False)

    username = forms.CharField(widget=forms.TextInput(attrs={
        'class':'form-control','placeholder':'', 'readonly':True}))
    email = forms.CharField(widget=forms.EmailInput(attrs={
        'class':'form-control','placeholder':'', 'readonly':True
    }))

shop/users/views.py
import json
from django.shortcuts import render, HttpResponseRedirect
from django.urls import reverse
from django.contrib import auth, messages
from django.contrib.auth.decorators import login_required
from pages.models import *
from .models import *
from .forms import *

def register(request):
    if request.method == 'POST':
        form = UserRegistrationForm(data=request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'Ви успішно створили новий аккаунт, саме час увійти')
            return HttpResponseRedirect(reverse('users:login'))
    else:
        form = UserRegistrationForm()
    pages = Page.objects.all()
    return render(request, "users/register.html", {'form':form, "pages":pages})

def login(request):
    if request.method == 'POST':
        form = UserLoginForm(data=request.POST)
        if form.is_valid():
            name = request.POST['username']
            pas = request.POST['password']
            user = auth.authenticate(username=name,password=pas)
            if user:
                auth.login(request,user)
                return HttpResponseRedirect(reverse('pages:index'))
    else:
        form = UserLoginForm()

    pages = Page.objects.all()
    context = {"form":form, "pages":pages}
    return render(request, "users/login.html",context)

@login_required
def single(request):
    if request.method == 'POST':
        form = UserCangeDataForm(instance=request.user, data=request.POST, files=request.FILES)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('users:single'))
    else:
        form = UserCangeDataForm(instance=request.user)
    return render(request, "users/single.html", {'form':form})

def logout(request):
    auth.logout(request)
    return HttpResponseRedirect(reverse('pages:index'))


def basket(request):
    pages = Page.objects.all()
    if request.user.is_authenticated:
        baskets = Basket.objects.filter(user=request.user,in_progress=False)

        return render(request, "users/basket.html", {'baskets': baskets, "pages":pages})
    else:
        baskett = request.COOKIES.get('baskets')
        if baskett:
            baskets = json.loads(baskett)
        else:
            baskets = {}
        total_sum = 0
        content = []
        for i in baskets:
            col,size,color = i.split(".")
            products=Product.objects.get(id=int(col))
            quantity = baskets[i]
            if products.sale:
                prise = products.prise_on_sale
            else:
                prise = products.price
            sum = prise*quantity
            total_sum += sum
            content.append({"product":products,"quantity":quantity,"price":prise,"sum":sum,
                            'size':size,'color':color})


        return render(request, "users/basket.html", {'baskets': content,"total_sum":total_sum, "pages":pages})

shop/users/templates/users/basket.html
{% extends 'pages/index2.html'%}
{% load static %}

{% block title %}
<title>Магія | Кошик з товарами</title>
<meta name="description" content="Заповнений кошик та оформлення замовлень">
<meta name="keywords" content="Кошик">
{% endblock %}

{% block body %}

<section class="row contained">



<div class="col-balance">
                <div class="card-side">
                    <!-- SIDE NAVIGATION OTHER BLOGS -->
                    <span class="fs-h3 ff-damion">Кошик</span>
                    <hr>
                    {% if baskets%}
                        {% if user.is_authenticated %}
                            {% for basket in baskets %}
                            <div class="row">
                            <div class="col-wide">
                            <a href="{% url 'pages:single' slug_prod=basket.product.slug %}" class="card-post">
                                <img src="{{basket.product.image.url}}" alt="">
                                <div class="info">
                                    <p class="no-margin fw-bold">{{basket.product.title}}</p>
                                    <small class="no-margin">{{basket.size}}</small>
                                    <small class="no-margin">{{basket.color}}</small>
                                    <small class="no-margin">{% if basket.product.sale %} {{basket.product.prise_on_sale}} {% else %} {{basket.product.price}} {%endif%}грн. * {{basket.quantity}}шт. = {{basket.sum}}грн. </small>

                                </div>
                            </a>
                            </div>
                            <div class="col-slim">
                                <a href="{% url 'pages:remove_basket' basket.id basket.product.id 0 0 %}" class="card-post" style="">
                                    Видалити
                                </a>
                            </div>
                            </div>
                            <hr>
                            {% endfor %}
                        <h3>Всього: {{baskets.total_sum}}грн.</h3>
                        {% else %}
<!--                                    <section class="contained ta-center" id="about" style="margin: 0; padding: 0; background: lightyellow; color:orangered;">-->
<!--                                        <h2 class="section-title ff-damion" style="background: orangered; color:lightyellow;">Увага!</h2>-->
<!--                                        <h3 class="col-wide mlmr-a">-->
<!--                                            Ви не увійшли в аккаунт. Обрані товари не будуть зберігатись довго-->
<!--                                        </h3>-->

<!--                                    </section>-->
                            {% for i in baskets %}
                            <div class="row">
                            <div class="col-wide">
                            <a href="{% url 'pages:single' slug_prod=i.product.slug %}" class="card-post">
                                <img src="{{i.product.image.url}}" alt="">
                                <div class="info">
                                    <p class="no-margin fw-bold">{{i.product.title}}</p>
                                    <small class="no-margin">{{i.size}}</small>
                                    <small class="no-margin">{{i.color}}</small>
                                    <small class="no-margin">{% if i.product.sale %} {{i.product.prise_on_sale}} {% else %} {{i.product.price}} {%endif%}грн. * {{i.quantity}}шт. = {{i.sum}}грн. </small>

                                </div>
                            </a>
                            </div>
                            <div class="col-slim">
                                <a href="{% url 'pages:remove_basket' 0 i.product.id i.size i.color%}" class="card-post" style="">
                                    Видалити
                                </a>
                            </div>
                            </div>
                            <hr>
                            {% endfor %}
                        <h3>Всього: {{total_sum}}грн.</h3>
                        {% endif %}

                    {% else %}
                    <h3>Покищо тут порожньо</h3>
                    {% endif %}

                </div>

</div>
<div class="col-balance">
    <div class="card-side">
                    <!-- SIDE NAVIGATION OTHER BLOGS -->
                    <span class="fs-h3 ff-damion">Замовлення</span>
                    <hr>
<!--        <div class="tabs">-->
<!--        &lt;!&ndash; Вкладки &ndash;&gt;-->
<!--        <input type="radio" id="tab1" name="tab-group" checked>-->
<!--        <label for="tab1" class="card-post">Вкладка 1</label>-->

<!--        <input type="radio" id="tab2" name="tab-group">-->
<!--        <label for="tab2" class="card-post">Вкладка 2</label>-->

<!--        <input type="radio" id="tab3" name="tab-group">-->
<!--        <label for="tab3" class="card-post">Вкладка 3</label>-->

<!--        &lt;!&ndash; Содержимое вкладок &ndash;&gt;-->
<!--        <div class="content">-->
<!--            <h3>Спосіб оплати:</h3>-->
<!--            <div class="tab-content" id="content1">-->
<!--                <p>Содержимое первой вкладки.</p>-->
<!--            </div>-->
<!--            <div class="tab-content" id="content2">-->
<!--                <p>Содержимое второй вкладки.</p>-->
<!--            </div>-->
<!--            <div class="tab-content" id="content3">-->
<!--                <form action="">-->
<!--                    -->
<!--                </form>-->
<!--            </div>-->
<!--        </div>-->
        <div class="row">
            {% if baskets%}
            <form action="{% url 'pages:thanks' %}" class="message-form" style="background: #ffffff; padding: 20px; border-radius: 25px; width: 100%" method="post">
                {% csrf_token %}
                <h3>Контактні данні</h3>
                <div class="row mb-20">
                <input type="text" id="surname" name="surname" class='' placeholder='Прізвище' required>
                <input type="text" id="name" name="name" class='ml-a' placeholder="Ім'я" required>
                </div>
                <div class="row mb-20">
                <input type="tel" id="phone" name="phone" pattern="\+\d{2} \(\d{3}\) \d{3} \d{2} \d{2}" placeholder="+ Номер телефону" required />
                <script>
                document.getElementById('phone').addEventListener('input', function (e) {
                  var x = e.target.value.replace(/\D/g, '');
                  if (x.length > 0) x = '+' + x;
                  if (x.length > 4) x = x.slice(0, 3) + ' (' + x.slice(3);
                  if (x.length > 9) x = x.slice(0, 8) + ') ' + x.slice(8);
                  if (x.length > 14) x = x.slice(0, 13) + ' ' + x.slice(13);
                  if (x.length > 17) x = x.slice(0, 16) + ' ' + x.slice(16,18);
                  e.target.value = x;
                });
                </script>
                </div>
                <hr>
                <h3>Місце та спосіб доставки</h3>
                <div class="row mb-20">
                <select id="sd" name="sd">
                  <option value="Nova poshta">Нова пошта</option>
                  <option value="Ukrposhta">Укрпошта</option>
                </select>

                </div>
                <div class="row mb-20">
                    <input type="text" id="city" name="city" class='' placeholder="Місто" required>
                <input type="text" id="adress" name="adress" class='ml-a' placeholder='Адресса'>
                </div>
                <hr>
                <textarea id="message-message" name="message-message" rows="5" placeholder="Додаткова інформація" ></textarea>




                    <button type="submit" class="btn-bg1 border-round mt-20">Замовити</button>
            {%else%}
                <form class="message-form" style="background: #ffffff; padding: 20px; border-radius: 25px; width: 100%">
                {% csrf_token %}
                <h3>Контактні данні</h3>
                <div class="row mb-20">
                <input type="text" id="surname" name="surname" class='' placeholder='Прізвище' required>
                <input type="text" id="name" name="name" class='ml-a' placeholder="Ім'я" required>
                </div>
                <div class="row mb-20">
                <input type="tel" id="phone" name="phone" pattern="\+\d{2} \(\d{3}\) \d{3} \d{2} \d{2}" placeholder="+ Номер телефону" required />
                <script>
                document.getElementById('phone').addEventListener('input', function (e) {
                  var x = e.target.value.replace(/\D/g, '');
                  if (x.length > 0) x = '+' + x;
                  if (x.length > 4) x = x.slice(0, 3) + ' (' + x.slice(3);
                  if (x.length > 9) x = x.slice(0, 8) + ') ' + x.slice(8);
                  if (x.length > 14) x = x.slice(0, 13) + ' ' + x.slice(13);
                  if (x.length > 17) x = x.slice(0, 16) + ' ' + x.slice(16,18);
                  e.target.value = x;
                });
                </script>
                </div>
                <hr>
                <h3>Місце та спосіб доставки</h3>
                <div class="row mb-20">
                <select id="sd" name="sd">
                  <option value="Nova poshta">Нова пошта</option>
                  <option value="Ukrposhta">Укрпошта</option>
                </select>

                </div>
                <div class="row mb-20">
                    <input type="text" id="city" name="city" class='' placeholder="Місто" required>
                <input type="text" id="adress" name="adress" class='ml-a' placeholder='Адресса'>
                </div>
                <hr>
                <textarea id="message-message" name="message-message" rows="5" placeholder="Додаткова інформація" ></textarea>




                    <a class="btn-bg1 border-round mt-20">Для початку покладіть щось в кошик</a>

                {%endif%}
            </form>

        </div>
    </div>
    </div>


                </div>
</div>

</section>





{% endblock %}

shop/users/templates/users/index.html
<!doctype html>

{% load static %}

<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="{% static 'css/mdb.dark.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/mdb.dark.rtl.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/mdb.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/mdb.rtl.min.css' %}">

    <link rel="stylesheet" href="{% static 'css/style.css' %}">

    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">

    {% block title%}

    {% endblock %}
</head>
<body>





<!-- Navbar -->
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <!-- Container wrapper -->
  <div class="container-fluid">
    <!-- Toggle button -->
    <button
      data-mdb-collapse-init
      class="navbar-toggler"
      type="button"
      data-mdb-target="#navbarSupportedContent"
      aria-controls="navbarSupportedContent"
      aria-expanded="false"
      aria-label="Toggle navigation"
    >
      <i class="fas fa-bars"></i>
    </button>

    <!-- Collapsible wrapper -->
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <!-- Navbar brand -->
      <a class="navbar-brand mt-2 mt-lg-0" href="#">
        <img
          src="https://mdbcdn.b-cdn.net/img/logo/mdb-transaprent-noshadows.webp"
          height="15"
          alt="MDB Logo"
          loading="lazy"
        />
      </a>
      <!-- Left links -->
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link" href="#">Dashboard</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">Team</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">Projects</a>
        </li>
      </ul>
      <!-- Left links -->
    </div>
    <!-- Collapsible wrapper -->

    <!-- Right elements -->
    <div class="d-flex align-items-center">
      <!-- Icon -->
      <a class="text-reset me-3" href="#">
        <i class="fas fa-shopping-cart"></i>
      </a>

      <!-- Notifications -->
      <div class="dropdown">
        <a
          data-mdb-dropdown-init
          class="text-reset me-3 dropdown-toggle hidden-arrow"
          href="#"
          id="navbarDropdownMenuLink"
          role="button"
          aria-expanded="false"
        >
          <i class="fas fa-bell"></i>
          <span class="badge rounded-pill badge-notification bg-danger">1</span>
        </a>
        <ul
          class="dropdown-menu dropdown-menu-end"
          aria-labelledby="navbarDropdownMenuLink"
        >
          <li>
            <a class="dropdown-item" href="#">Some news</a>
          </li>
          <li>
            <a class="dropdown-item" href="#">Another news</a>
          </li>
          <li>
            <a class="dropdown-item" href="#">Something else here</a>
          </li>
        </ul>
      </div>
      <!-- Avatar -->
      <div class="dropdown">
        <a
          data-mdb-dropdown-init
          class="dropdown-toggle d-flex align-items-center hidden-arrow"
          href="#"
          id="navbarDropdownMenuAvatar"
          role="button"
          aria-expanded="false"
        >
          <img
            src="https://mdbcdn.b-cdn.net/img/new/avatars/2.webp"
            class="rounded-circle"
            height="25"
            alt="Black and White Portrait of a Man"
            loading="lazy"
          />
        </a>
        <ul
          class="dropdown-menu dropdown-menu-end"
          aria-labelledby="navbarDropdownMenuAvatar"
        >
          <li>
            <a class="dropdown-item" href="#">My profile</a>
          </li>
          <li>
            <a class="dropdown-item" href="#">Settings</a>
          </li>
          <li>
            <a class="dropdown-item" href="#">Logout</a>
          </li>
        </ul>
      </div>
    </div>
    <!-- Right elements -->
  </div>
  <!-- Container wrapper -->
</nav>
<!-- Navbar -->

    {% block body%}

    {% endblock %}




<!-- Footer -->
<foot class="text-center text-lg-start bg-body-tertiary text-muted bg-dark">
  <!-- Section: Social media -->
  <section class="d-flex justify-content-center justify-content-lg-between p-4 border-bottom bg-dark">
    <!-- Left -->
    <div class="me-5 d-none d-lg-block">
      <span>Get connected with us on social networks:</span>
    </div>
    <!-- Left -->

    <!-- Right -->
    <div>
      <a href="" class="me-4 text-reset">
        <i class="fab fa-facebook-f"></i>
      </a>
      <a href="" class="me-4 text-reset">
        <i class="fab fa-twitter"></i>
      </a>
      <a href="" class="me-4 text-reset">
        <i class="fab fa-google"></i>
      </a>
      <a href="" class="me-4 text-reset">
        <i class="fab fa-instagram"></i>
      </a>
      <a href="" class="me-4 text-reset">
        <i class="fab fa-linkedin"></i>
      </a>
      <a href="" class="me-4 text-reset">
        <i class="fab fa-github"></i>
      </a>
    </div>
    <!-- Right -->
  </section>
  <!-- Section: Social media -->

  <!-- Section: Links  -->
  <section class="">
    <div class="container text-center text-md-start mt-5">
      <!-- Grid row -->
      <div class="row mt-3">
        <!-- Grid column -->
        <div class="col-md-3 col-lg-4 col-xl-3 mx-auto mb-4">
          <!-- Content -->
          <h6 class="text-uppercase fw-bold mb-4">
            <i class="fas fa-gem me-3"></i>Company name
          </h6>
          <p>
            Here you can use rows and columns to organize your footer content. Lorem ipsum
            dolor sit amet, consectetur adipisicing elit.
          </p>
        </div>
        <!-- Grid column -->

        <!-- Grid column -->
        <div class="col-md-2 col-lg-2 col-xl-2 mx-auto mb-4">
          <!-- Links -->
          <h6 class="text-uppercase fw-bold mb-4">
            Products
          </h6>
          <p>
            <a href="#!" class="text-reset">Angular</a>
          </p>
          <p>
            <a href="#!" class="text-reset">React</a>
          </p>
          <p>
            <a href="#!" class="text-reset">Vue</a>
          </p>
          <p>
            <a href="#!" class="text-reset">Laravel</a>
          </p>
        </div>
        <!-- Grid column -->

        <!-- Grid column -->
        <div class="col-md-3 col-lg-2 col-xl-2 mx-auto mb-4">
          <!-- Links -->
          <h6 class="text-uppercase fw-bold mb-4">
            Useful links
          </h6>
          <p>
            <a href="#!" class="text-reset">Pricing</a>
          </p>
          <p>
            <a href="#!" class="text-reset">Settings</a>
          </p>
          <p>
            <a href="#!" class="text-reset">Orders</a>
          </p>
          <p>
            <a href="#!" class="text-reset">Help</a>
          </p>
        </div>
        <!-- Grid column -->

        <!-- Grid column -->
        <div class="col-md-4 col-lg-3 col-xl-3 mx-auto mb-md-0 mb-4">
          <!-- Links -->
          <h6 class="text-uppercase fw-bold mb-4">Contact</h6>
          <p><i class="fas fa-home me-3"></i> New York, NY 10012, US</p>
          <p>
            <i class="fas fa-envelope me-3"></i>
            info@example.com
          </p>
          <p><i class="fas fa-phone me-3"></i> + 01 234 567 88</p>
          <p><i class="fas fa-print me-3"></i> + 01 234 567 89</p>
        </div>
        <!-- Grid column -->
      </div>
      <!-- Grid row -->
    </div>
  </section>
  <!-- Section: Links  -->

  <!-- Copyright -->
  <div class="text-center p-4" style="background-color: rgba(0, 0, 0, 0.05);">
    © 2021 Copyright:
    <a class="text-reset fw-bold" href="https://mdbootstrap.com/">MDBootstrap.com</a>
  </div>
  <!-- Copyright -->
</foot>
<!-- Footer -->

</body>
<footer>
    <script type="text/javascript" src="{% static 'js/mdb.es.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/mdb.umd.min.js' %}"></script>
</footer>
</html>

shop/users/templates/users/login.html
{% extends 'pages/index2.html'%}
{% load static %}

{% block title %}
<title>Магія | Вхід в аккаунт</title>
<meta name="description" content="Сторінка входу у власний аккаунт користувача">
<meta name="keywords" content="Вхід в аккаунт">
{% endblock %}

{% block body %}

{% if messages %}
{% for message in messages %}

        <section class="contained" style="background: lightgreen; color:green;">
            <h2 class="section-title ff-damion" style="background: green; color:lightgreen;">Успішно</h2>
            <p class="col-wide ta-center mlmr-a">
                {{ message }}

            </p>
        </section>

{% endfor %}
{% endif %}

{% if form.non_field_errors %}

        <section class="contained" style="background: lightyellow; color:orangered;">
            <h2 class="section-title ff-damion" style="background: orangered; color:lightyellow;">Щось пішло не так</h2>
            <p class="col-wide ta-center mlmr-a">
                {{ form.non_field_errors }}
            </p>
        </section>


{% endif %}

        <section class="contained">
            <h2 class="section-title ff-damion">Вхід в аккаунт</h2>

            <div class="row">
            <div class="col-balance">

              <form action="{% url 'users:login' %}" class="message-form mt-50 mb-25" method="post">
                  {% csrf_token %}
                  <div class="row mb-20">
                    {{form.username}}
                    {{form.password}}
                     </div>
                   <button type="submit" class="btn-bg1 border-round mt-20">Вхід</button>
              </form>

            </div>
            </div>
        </section>




{% endblock %}

shop/users/templates/users/register.html
{% extends 'pages/index2.html'%}
{% load static %}

{% block title %}
<title>Магія | Зареєструватися</title>
<meta name="description" content="Сторінка реєстрації нових користувачів">
<meta name="keywords" content="Реєстрація">
{% endblock %}

{% block body %}


{% if form.errors %}

        <section class="contained" style="background: pink; color:darkred;">
            <h2 class="section-title ff-damion" style="background: darkred; color:pink;">Помилка</h2>
            <p class="col-wide ta-center mlmr-a">
                {{ form.errors }}

            </p>
        </section>

{% endif %}

<section class="contained">
            <h2 class="section-title ff-damion">Зареєструватись</h2>




              <form action="{% url 'users:register' %}" class="message-form mt-50 mb-25" method="post">
                  {% csrf_token %}
                  <div class="row mb-20">
                    {{form.first_name}}
                    {{form.last_name}}

                     </div>
                <div class="row mb-20">
                    {{form.username}}
                    {{form.email}}

                     </div>
                <div class="row mb-20">


                    {{form.password1}}
                    {{form.password2}}
                     </div>

                   <button type="submit" class="btn-bg1 border-round mt-20">Завершити</button>
              </form>
    <p>Вже є аккаунт?</p>
                <a type="submit" href="{%url 'users:login'%}" class="btn-bg1 border-round mt-20">Увійти</a>



        </section>

{% endblock %}

shop/users/templates/users/single.html
{% extends 'pages/index2.html'%}
{% load static %}

{% block body %}

{% if form.non_field_errors %}
  {{ form.non_field_errors }}
{% endif %}

<img src="{% if user.image %} {{user.image.url}} {% else %} {% static 'img/mdb-favicon.ico' %} {% endif %}" alt="">


<form action="{% url 'users:single' %}" method="post" enctype="multipart/form-data">
    {{form.as_p}}
    {% csrf_token %}

  <button data-mdb-ripple-init type="submit" class="btn btn-primary btn-block">Update</button>
</form>



{% endblock %}